# Generated by matugen from quickshell/matugen/templates/fish-colors.fish.

# Syntax highlighting.
set -g fish_color_normal {{colors.on_surface.dark.hex_stripped}}
set -g fish_color_command {{colors.primary.dark.hex_stripped}}
set -g fish_color_keyword {{colors.tertiary.dark.hex_stripped}}
set -g fish_color_quote {{colors.secondary.dark.hex_stripped}}
set -g fish_color_redirection {{colors.on_surface_variant.dark.hex_stripped}}
set -g fish_color_end {{colors.tertiary.dark.hex_stripped}}
set -g fish_color_error {{colors.error.dark.hex_stripped}}
set -g fish_color_param {{colors.on_surface.dark.hex_stripped}}
set -g fish_color_comment {{colors.outline.dark.hex_stripped}}
set -g fish_color_selection --background={{colors.primary_container.dark.hex_stripped}}
set -g fish_color_operator {{colors.tertiary.dark.hex_stripped}}
set -g fish_color_escape {{colors.secondary.dark.hex_stripped}}
set -g fish_color_autosuggestion {{colors.outline.dark.hex_stripped}}
set -g fish_color_cancel {{colors.error.dark.hex_stripped}}
set -g fish_color_search_match --background={{colors.primary_container.dark.hex_stripped}}
set -g fish_color_valid_path --underline

# Completion pager.
set -g fish_pager_color_progress {{colors.on_surface_variant.dark.hex_stripped}}
set -g fish_pager_color_prefix {{colors.primary.dark.hex_stripped}}
set -g fish_pager_color_completion {{colors.on_surface.dark.hex_stripped}}
set -g fish_pager_color_description {{colors.outline.dark.hex_stripped}}
set -g fish_pager_color_selected_background --background={{colors.primary_container.dark.hex_stripped}}

# fzf gets the same palette.
set -q __yonux_fzf_base; or set -g __yonux_fzf_base $FZF_DEFAULT_OPTS
set -gx FZF_DEFAULT_OPTS "$__yonux_fzf_base \
--color=fg:{{colors.on_surface.dark.hex}},bg:-1,hl:{{colors.primary.dark.hex}} \
--color=fg+:{{colors.on_surface.dark.hex}},bg+:{{colors.primary_container.dark.hex}},hl+:{{colors.primary.dark.hex}} \
--color=info:{{colors.secondary.dark.hex}},prompt:{{colors.primary.dark.hex}},pointer:{{colors.tertiary.dark.hex}} \
--color=marker:{{colors.tertiary.dark.hex}},spinner:{{colors.secondary.dark.hex}},header:{{colors.outline.dark.hex}} \
--color=border:{{colors.outline_variant.dark.hex}}"

set -g __yonux_colors_file (status filename)
function __yonux_colors_reload --on-variable __yonux_colors_rev
    source $__yonux_colors_file
end
