-- Generated by matugen from quickshell/matugen/templates/hypr-colors.lua.
-- Loaded by hypr/modules/decoration.lua, and by `hyprctl eval` on every
-- wallpaper change.
hl.config({
    general = {
        ["col.active_border"] = "rgb({{colors.primary.dark.hex_stripped}})",
        ["col.inactive_border"] = "rgb({{colors.surface.dark.hex_stripped}})",
    },
})
